# Generated by Django 5.2 on 2025-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rollno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
