# Generated by Django 5.2 on 2025-10-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stream',
            field=models.CharField(default='Not selected', max_length=30),
        ),
    ]
